name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  build_test_deploy:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.1.3'
      - uses: r-lib/actions/setup-renv@v2
      - name: Install extra dependencies
        run: Rscript -e "install.packages('remotes', 'testthat')" -e "remotes::install_github('jimhester/lintr')"
      - name: Linting
        run: quit(save = "no", status = length(lintr::lint_dir()))
        shell: Rscript {0}
      - name: Testing
        run: test_dir("tests")
        shell: Rscript {0}
      - if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "shiny-wordcloudgenerator"
          heroku_email: "thangnv2212@gmail.com"
          healthcheck: https://shiny-wordcloudgenerator.herokuapp.com/
          rollbackonhealthcheckfailed: true

  tag_release:
    needs: [build_test_deploy]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch